### PR TITLE
New config-API-features

### PR DESCRIPTION
**Pull request by SCDerox**
To improve the user experience in the SCNX Dashboard, several new API-Features for config-example-files are planned. 

Currently new features:
* content.elementToggle: Hides all other fields of the Config-Element (/file) in the Dashboard if disabled. [Demo](https://user-images.githubusercontent.com/43812987/194376419-38772088-bd8c-40a0-866a-5d00348c449c.mp4).
* content.dependsOn: References an other boolean-field. If the referenced field is disabled, this field will get hidden. [Demo](https://user-images.githubusercontent.com/43812987/194622438-5d7ccae9-2088-4900-8d31-fecc9a5357f9.mp4) 
* New field-type: `userID` ([Demo](https://user-images.githubusercontent.com/43812987/194871559-b53c4243-eb24-4ef4-ae4e-4fe4bfd86585.png))
* New field-type: `imgURL` ([Demo](https://user-images.githubusercontent.com/43812987/194880821-6e8fe34a-32a1-4d6a-81de-74ebfa5d3803.png))

This PR is WIP, meaning new fields may get added later.

Feel free to comment features you'd 

like to see in the Dashboard for config-example-files.

### CODE REVIEW

**Comment by SCDerox** [comment]
New: Support for `content.dependsOn` field. Watch [this demo](https://user-images.githubusercontent.com/43812987/194622438-5d7ccae9-2088-4900-8d31-fecc9a5357f9.mp4) to view it in action.

**Comment by jateute** [comment]
It might also be practical to have a user Type (input for a Discord-UserID)

**Comment by SCDerox** [comment]
Thanks, @jateute, we've added support for it ([preview](https://user-images.githubusercontent.com/43812987/194871456-459fcdda-3da9-4fb4-af10-5daae1109ed7.png))

**Comment by SCDerox** [comment]
New: We've added support for `imgURL`-field-types. [View demo](https://user-images.githubusercontent.com/43812987/194876677-e5e155b5-d4fa-4b06-86be-39ef6dc3dfe1.png).

**Pull request merged**
